services:
  - type: web
    name: fitai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    pythonVersion: 3.12

  - type: static
    name: fitai-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/build
    plan: free
